enhancement:
  - feat-*
  - feat/*
  - feature-*
  - feature/*

bug:
  - fix-*
  - fix/*
  - bugfix-*
  - bugfix/*
  - bug-*
  - bug/*

chore:
  - chore-*
  - chore/*

# Labels are also automatically added by renovate
dependencies:
  - renovate/*

content:
  - content-*
  - content/*
